version: '3.2'
# you need a newer version of docker(& docker-compose) for the newer configurations
services:
  spid-testenv-backoffice:
    container_name: spid-testenv-backoffice
    # we build using the local Dockerfile
    build: ./backoffice
    # the tag image is used during the build for tagging
    image: fe/spid-backoffice:latest
    # change the ports if they are already binded by another application or container
    ports:
      - "8080:8080"
    # we bind the configuration file with the local file and export the container keystore directory
    environment:
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    #depends_on:
    #  - spid-testenv-identityserver
  spid-testenv-identityserver:
    container_name: spid-testenv-identityserver
    build: ./identity-server
# we used directly the DockerHub image. If you need to override the build edit the dockerfile and uncomment the build directive
    image: italia/spid-testenv-identityserver:local
    # we mount the keystore from the spid-testenv-backoffice directly into the the container
    ports:
      - "9443:9443"

  
# persistence & shared volumes
volumes:
  keystore:
  idp:
