# Identity Server
FROM italia/spid-testenv-identityserver:docker-compose
LABEL MAINTAINER Francesco Pirrone <francesco.pirrone@finance-evolution.com>
COPY certs /spid-testenvironment/is/identity-server/repository/resources/security

# Port exposed
EXPOSE 9443

